# .github/workflows/deploy.yml
name: Deploy Next.js App to Plesk

on:
  push:
    branches:
      - main  # Adjust to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Adjust according to your app's requirements

    - name: Install dependencies
      run: npm install

    - name: Build the Next.js app
      run: npm run build

    - name: Export Next.js app
      run: npm run export

    - name: Deploy to Plesk via SFTP
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.PLESK_HOST }}
        username: ${{ secrets.PLESK_USERNAME }}
        password: ${{ secrets.PLESK_PASSWORD }}
        port: ${{ secrets.PLESK_PORT }}
        source: "out/*"                # Next.js exports to the 'out' directory
        target: "${{ secrets.PLESK_DEPLOY_PATH }}"
        rm: true                         # Optional: Removes files not in the source

    - name: Confirm deployment
      run: echo "Deployment to Plesk completed."
